version: "3.9"

services:
    django-aplication-dev:
        extends:
            file: docker-compose.yml
            service: django-aplication
        container_name: app-dev
        build:
            target: dev
        volumes:
            - "./:/app"
        # Force the container to stay alive
        tty: true
