# Generated by Django 5.0 on 2023-12-05 16:20

import django.db.models.expressions
import django.db.models.functions.datetime
import django.db.models.functions.math
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyDeafultFieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(db_default=models.Value(18))),
                ('created', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('circumference', models.FloatField(db_default=django.db.models.expressions.CombinedExpression(models.Value(2), '*', django.db.models.functions.math.Pi()))),
            ],
        ),
        migrations.CreateModel(
            name='Square',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.IntegerField()),
                ('area', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('side'), '*', models.F('side')), output_field=models.BigIntegerField())),
            ],
        ),
    ]
