# Generated by Django 5.0 on 2023-12-24 20:17

import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfeaturesdiscovery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydeafultfieldmodel',
            name='age',
            field=models.IntegerField(db_default=models.Value(18), default=17),
        ),
        migrations.AlterField(
            model_name='mydeafultfieldmodel',
            name='created',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now),
        ),
    ]
